# Generated by Django 5.1.5 on 2025-01-31 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_id', models.IntegerField(unique=True)),
                ('fname', models.CharField(max_length=80)),
                ('lname', models.CharField(max_length=80)),
                ('div', models.CharField(max_length=10)),
                ('mail', models.EmailField(max_length=254)),
                ('marks', models.FloatField()),
            ],
        ),
    ]
